### ISSUE TITLE
web协议的能不能获取到网页的Cookies 等 headers信息

### ISSUE THREAD

**Issue by yh4922** [wechaty/wechaty-puppet-puppeteer#114]
web协议的能不能获取到网页的Cookies 等 headers信息
需要获取到 网页微信的 header 信息

**Comment by yh4922** [comment]
有地方可以获取到么

**Comment by huan** [comment]
Of course, you could. Please feel free to look into the code and find the data by your self.

You can start here:

https://github.com/Chatie/wechaty-puppet-puppeteer/blob/f87b40bb735354f1229e242f9f3162017231c355/src/bridge.ts#L969-L987

**Comment by yh4922** [comment]
找到了  谢谢  
之前一直在 wechaty 的源码里面找

**Comment by huan** [comment]
Had your problem solved?

Please help us to close the issue if you have no more questions, thanks.
